workflows:
  default-workflow:
    name: Ionic Android
    max_build_duration: 60
    environment:
      vars:
          GRADLE_PATH: /Users/builder/programs/gradle-5.6.4/bin
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
     - npm install
     - npm install -g ionic
     - ionic cordova platform add android
     - ionic cordova build android
    artifacts:
     - android/app/build/outputs/**/**/*.apk
     - android/app/build/outputs/**/**/*.aab
     - /tmp/xcodebuild_logs/*.log 
     - $FCI_BUILD_DIR/*.zip
    publishing:
      email:
        recipients:
          - dreamcodesoft@gmail.com
