workflows:
  default-workflow:
    name: Ionic Android
    max_build_duration: 60
    environment:
      vars:
          GRADLE_PATH: /Users/builder/programs/gradle-5.6.4/bin
          ANDROID_SDK_ROOT: /Users/builder/programs/android-sdk-macosx
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
     - npm install
     - npm install -g ionic
     - ionic cordova platform add android
     - echo $GRADLE_PATH
     - export PATH=$GRADLE_PATH:$PATH
     - echo $PATH
     - export PATH=$GRADLE_PATH:$PATH && ionic cordova build android
    artifacts:
     - platforms/android/app/build/outputs/apk/**/*.apk
     - platforms/android/app/build/outputs/apk/**/*.aab
     - /tmp/xcodebuild_logs/*.log 
     - $FCI_BUILD_DIR/*.zip
    publishing:
      email:
        recipients:
          - dreamcodesoft@gmail.com
